version: '2'
services:
    sleague-app:
        image: sleague
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sleague-postgresql:5432/sleague
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sleague-postgresql:
        extends:
            file: postgresql.yml
            service: sleague-postgresql
